const { chromium } = require('playwright');
const path = require('path');
const fs = require('fs');
const { execSync } = require('child_process');

const RECORD_DIR = path.resolve(__dirname, '../recordings');
const ARTIFACT_DIR = path.resolve('C:/Users/admin/.gemini/antigravity/brain/2d86aae9-c430-40ad-b643-4d6a580f5293');
if (!fs.existsSync(RECORD_DIR)) {
  fs.mkdirSync(RECORD_DIR, { recursive: true });
}

// Load exact sync manifest generated by edge-tts
const manifestPath = path.join(RECORD_DIR, 'sync_manifest.json');
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
console.log(`Loaded Sync Manifest: ${manifest.scenes.length} scenes, total ${manifest.total_duration}s`);

const delay = ms => new Promise(r => setTimeout(r, ms));

// Smooth camera transition using browser-native RAF physics controller
async function smoothCameraTo(page, targetDx, targetDy, scale = 1.20, dur = 650) {
  const minDx = (1 - scale) * 1280;
  const minDy = (1 - scale) * 720;
  const clampedDx = Math.max(minDx, Math.min(0, targetDx));
  const clampedDy = Math.max(minDy, Math.min(0, targetDy));

  await page.evaluate(async ({ dx, dy, s, d }) => {
    if (window.__smoothCameraTo) {
      await window.__smoothCameraTo(dx, dy, s, d);
    }
  }, { dx: clampedDx, dy: clampedDy, s: scale, d: dur });
}

// Dynamic element-aware camera targeter: finds exact element rect, untransforms it, centers it, and clamps
async function smoothCameraToElement(page, selector, { scale = 1.20, dur = 650, offsetX = 0, offsetY = 0, focusX = 640, focusY = 360 } = {}) {
  const result = await page.evaluate(({ sel, s, fx, fy, ox, oy }) => {
    const el = document.querySelector(sel);
    if (!el) return null;
    const r = el.getBoundingClientRect();
    const cam = window.__camera || { curDx: 0, curDy: 0, curScale: 1.0 };
    
    // Viewport position of element center:
    const vcx = r.left + r.width / 2;
    const vcy = r.top + r.height / 2;
    
    // Convert to untransformed body coordinates:
    const origCx = (vcx - cam.curDx) / cam.curScale;
    const origCy = (vcy - cam.curDy) / cam.curScale;
    
    // Desired viewport focal point:
    const targetFx = fx + ox;
    const targetFy = fy + oy;
    
    // Target translation to map orig to focal point:
    let targetDx = targetFx - s * origCx;
    let targetDy = targetFy - s * origCy;
    
    const minDx = (1 - s) * 1280;
    const minDy = (1 - s) * 720;
    targetDx = Math.max(minDx, Math.min(0, targetDx));
    targetDy = Math.max(minDy, Math.min(0, targetDy));
    
    return { dx: targetDx, dy: targetDy, s };
  }, { sel: selector, s: scale, fx: focusX, fy: focusY, ox: offsetX, oy: offsetY });

  if (result) {
    await page.evaluate(async ({ dx, dy, s, d }) => {
      if (window.__smoothCameraTo) {
        await window.__smoothCameraTo(dx, dy, s, d);
      }
    }, { dx: result.dx, dy: result.dy, s: result.s, d: dur });
  } else {
    console.warn(`[smoothCameraToElement] Element not found: ${selector}`);
  }
}

// Reset camera to wide 1.0 scale with smooth ease
async function resetCamera(page, dur = 650) {
  await page.evaluate(async ({ d }) => {
    if (window.__smoothCameraTo) {
      await window.__smoothCameraTo(0, 0, 1.0, d);
    }
  }, { d: dur });
}

// Organic fast interpolated cursor glide with Promise synchronization
async function glideCursor(page, targetX, targetY, durationMs = 400) {
  await page.evaluate(async ({ tx, ty, dur }) => {
    if (window.__glideCursor) {
      await window.__glideCursor(tx, ty, dur);
    } else if (window.__updateCursor) {
      window.__updateCursor(tx, ty);
    }
  }, { tx: targetX, ty: targetY, dur: durationMs });
  await delay(50);
}

// Glide cursor to center of live element on screen
async function glideCursorToElement(page, selector, glideDur = 400, fallbackX = null, fallbackY = null) {
  try {
    const element = page.locator(selector).first();
    const box = await element.boundingBox({ timeout: 2500 });
    if (box) {
      const targetX = box.x + box.width / 2;
      const targetY = box.y + box.height / 2;
      await glideCursor(page, targetX, targetY, glideDur);
      return { x: targetX, y: targetY };
    }
  } catch (e) {}

  if (fallbackX !== null && fallbackY !== null) {
    await glideCursor(page, fallbackX, fallbackY, glideDur);
    return { x: fallbackX, y: fallbackY };
  }
  return null;
}

// Glide to element, trigger click ripple, and click
async function glideAndClick(page, selector, glideDur = 400, postClickWait = 200) {
  const element = page.locator(selector).locator('visible=true').first();
  await element.waitFor({ state: 'visible', timeout: 8000 });
  const box = await element.boundingBox();
  if (!box) return;

  const targetX = box.x + box.width / 2;
  const targetY = box.y + box.height / 2;

  await glideCursor(page, targetX, targetY, glideDur);
  await delay(100);

  // Trigger ripple at exact cursor tip
  await page.evaluate(({ x, y }) => {
    if (window.__triggerRipple) window.__triggerRipple(x, y);
  }, { x: targetX, y: targetY });

  await element.click({ force: true });
  await delay(postClickWait);
}

// Type text naturally
async function typeTextHuman(page, selector, text, keyDelay = 65) {
  await glideAndClick(page, selector, 350, 100);
  for (const char of text) {
    await page.locator(selector).first().pressSequentially(char, { delay: keyDelay });
  }
  await delay(120);
}

// Precision Scene Orchestrator: locks each scene duration to audio length
async function runScene(sceneIdx, actionFn) {
  const sceneInfo = manifest.scenes[sceneIdx - 1];
  const targetDurationMs = sceneInfo.duration * 1000;
  console.log(`\n📍 Scene ${sceneIdx}: ${sceneInfo.filename} (Target: ${sceneInfo.duration}s)`);
  const startTime = Date.now();
  
  await actionFn();
  
  const elapsed = Date.now() - startTime;
  const remaining = targetDurationMs - elapsed;
  if (remaining > 0) {
    console.log(`   [Holding scene ${sceneIdx} for remaining ${(remaining/1000).toFixed(2)}s to match audio]`);
    await delay(remaining);
  } else {
    console.log(`   [Scene ${sceneIdx} finished with overrun of ${(-remaining/1000).toFixed(2)}s]`);
  }
}

(async () => {
  console.log('🎬 Starting Master Tutorial Recording with Native RAF Camera & Exact DOM Sync...');

  const browser = await chromium.launch({
    headless: true
  });

  const context = await browser.newContext({
    viewport: { width: 1280, height: 720 },
    deviceScaleFactor: 1,
    recordVideo: {
      dir: RECORD_DIR,
      size: { width: 1280, height: 720 }
    }
  });

  const page = await context.newPage();
  const recStartTime = Date.now();

  page.on('dialog', async d => { await d.accept(); });

  // Inject virtual cursor & RAF physics camera engine
  await page.addInitScript(() => {
    window.alert = () => {};
    window.prompt = () => '';

    // Camera State
    window.__camera = {
      curDx: 0,
      curDy: 0,
      curScale: 1.0,
      animId: null
    };

    // 60 FPS requestAnimationFrame Physics Camera Controller
    window.__smoothCameraTo = (targetDx, targetDy, targetScale, duration = 650) => {
      return new Promise((resolve) => {
        if (window.__camera.animId) {
          cancelAnimationFrame(window.__camera.animId);
          window.__camera.animId = null;
        }
        const startDx = window.__camera.curDx;
        const startDy = window.__camera.curDy;
        const startScale = window.__camera.curScale;
        const startTime = performance.now();

        document.body.style.willChange = 'transform';
        document.body.style.transformOrigin = '0 0';
        document.body.style.backfaceVisibility = 'hidden';

        function step(now) {
          const elapsed = now - startTime;
          const progress = Math.min(1, elapsed / duration);
          
          // Apple WWDC fluid quintic ease-out curve:
          // 1 - (1 - p)^4.2 gives zero jerk at start and physical critically-damped deceleration
          const ease = 1 - Math.pow(1 - progress, 4.2);
          
          window.__camera.curDx = startDx + (targetDx - startDx) * ease;
          window.__camera.curDy = startDy + (targetDy - startDy) * ease;
          window.__camera.curScale = startScale + (targetScale - startScale) * ease;
          
          document.body.style.transform = `translate3d(${window.__camera.curDx.toFixed(2)}px, ${window.__camera.curDy.toFixed(2)}px, 0) scale(${window.__camera.curScale.toFixed(4)})`;

          if (progress < 1) {
            window.__camera.animId = requestAnimationFrame(step);
          } else {
            window.__camera.curDx = targetDx;
            window.__camera.curDy = targetDy;
            window.__camera.curScale = targetScale;
            document.body.style.transform = `translate3d(${targetDx.toFixed(2)}px, ${targetDy.toFixed(2)}px, 0) scale(${targetScale.toFixed(4)})`;
            window.__camera.animId = null;
            resolve();
          }
        }
        window.__camera.animId = requestAnimationFrame(step);
      });
    };

    window.addEventListener('DOMContentLoaded', () => {
      const style = document.createElement('style');
      style.innerHTML = `
        #virtual-cursor {
          position: fixed;
          width: 28px;
          height: 28px;
          top: 0;
          left: 0;
          pointer-events: none;
          z-index: 2147483647;
          transform: translate3d(640px, 360px, 0);
          will-change: transform;
        }
        #virtual-cursor-pointer {
          width: 100%;
          height: 100%;
          filter: drop-shadow(0 3px 6px rgba(0,0,0,0.55));
        }
        .click-ripple {
          position: fixed;
          border: 3px solid #ff3b30;
          border-radius: 50%;
          pointer-events: none;
          z-index: 2147483646;
          animation: rippleEffect 0.55s ease-out forwards;
        }
        @keyframes rippleEffect {
          0% { width: 6px; height: 6px; opacity: 1; transform: translate(-50%, -50%) scale(1); }
          100% { width: 56px; height: 56px; opacity: 0; transform: translate(-50%, -50%) scale(2.2); }
        }
      `;
      document.head.appendChild(style);

      const cursor = document.createElement('div');
      cursor.id = 'virtual-cursor';
      cursor.innerHTML = `
        <svg id="virtual-cursor-pointer" viewBox="0 0 24 24" fill="none">
          <path d="M4 2L20 10L12 12L10 20L4 2Z" fill="#ff3b30" stroke="#ffffff" stroke-width="2" stroke-linejoin="round"/>
        </svg>
      `;
      document.documentElement.appendChild(cursor);

      let curX = 640;
      let curY = 360;
      let cursorAnimId = null;

      window.__updateCursor = (x, y) => {
        curX = x; curY = y;
        cursor.style.transform = `translate3d(${x}px, ${y}px, 0)`;
      };

      // Organic quintic ease-out cursor glide
      window.__glideCursor = (targetX, targetY, duration = 380) => {
        return new Promise((resolve) => {
          if (cursorAnimId) cancelAnimationFrame(cursorAnimId);
          const startX = curX;
          const startY = curY;
          const startTime = performance.now();

          function step(now) {
            const elapsed = now - startTime;
            const progress = Math.min(1, elapsed / duration);
            const ease = 1 - Math.pow(1 - progress, 4.0);
            curX = startX + (targetX - startX) * ease;
            curY = startY + (targetY - startY) * ease;
            cursor.style.transform = `translate3d(${curX.toFixed(2)}px, ${curY.toFixed(2)}px, 0)`;

            if (progress < 1) {
              cursorAnimId = requestAnimationFrame(step);
            } else {
              curX = targetX;
              curY = targetY;
              cursor.style.transform = `translate3d(${targetX.toFixed(2)}px, ${targetY.toFixed(2)}px, 0)`;
              cursorAnimId = null;
              resolve();
            }
          }
          cursorAnimId = requestAnimationFrame(step);
        });
      };

      window.__triggerRipple = (x, y) => {
        const ripple = document.createElement('div');
        ripple.className = 'click-ripple';
        ripple.style.left = x + 'px';
        ripple.style.top = y + 'px';
        document.documentElement.appendChild(ripple);
        setTimeout(() => ripple.remove(), 600);
      };
    });
  });

  await page.goto('http://127.0.0.1:8080/');
  await page.waitForLoadState('networkidle');
  await delay(600);

  const preRollOffsetSec = (Date.now() - recStartTime) / 1000;
  fs.writeFileSync(path.join(RECORD_DIR, 'pre_roll_offset.txt'), preRollOffsetSec.toFixed(3));
  console.log(`⏱️ Pre-roll offset measured: ${preRollOffsetSec.toFixed(3)}s`);

  // ──────────────────────────────────────────────────────────────────────────
  // SCENE 1: Welcome to Guess The Frame & Create Room (5.472s)
  // Audio: "Welcome to Guess The Frame! To host a game with your friends, click Create Room."
  // ──────────────────────────────────────────────────────────────────────────
  await runScene(1, async () => {
    // 0.0s - 1.8s: "Welcome to Guess The Frame!" -> Wide hero shot, cursor drifts near center title
    await glideCursor(page, 640, 260, 500);
    await delay(1200);

    // 1.8s - 3.4s: "To host a game with your friends," -> Smooth 650ms zoom to Create Room card
    await smoothCameraToElement(page, '.h-card-create', { scale: 1.20, dur: 650 });
    await glideCursorToElement(page, '.h-card-create', 380);
    await delay(400);

    // 3.4s - 5.47s: "click Create Room." -> Click with ripple at ~3.8s, modal opens
    await glideAndClick(page, '.h-card-create', 350, 800);
  });

  // ──────────────────────────────────────────────────────────────────────────
  // SCENE 2: Character Setup: Name & Avatar (6.120s)
  // Audio: "Type in your player name, pick your favorite animated avatar, and hit Enter to join your lobby."
  // ──────────────────────────────────────────────────────────────────────────
  await runScene(2, async () => {
    // 0.0s - 2.2s: "Type in your player name," -> Smooth zoom into modal box (scale 1.14 keeps entire box in frame)
    await smoothCameraToElement(page, '#createRoomModal .mp-modal-box', { scale: 1.14, dur: 650 });
    await typeTextHuman(page, '#hostPlayerNameInput', 'Aman', 65);
    await delay(300);

    // 2.2s - 4.0s: "pick your favorite animated avatar," -> Glide to Aman avatar, click with pink highlight
    await glideAndClick(page, '#createRoomModal .mp-avatar-option[data-avatar="aman"]', 350, 400);
    await delay(300);

    // 4.0s - 6.12s: "and hit Enter to join your lobby." -> Glide to Create Room & Get Code, click
    await glideAndClick(page, '#createRoomModal .mp-btn-primary', 380, 700);
  });

  // ──────────────────────────────────────────────────────────────────────────
  // SCENE 3: Select Rounds & Share Invite Link (7.728s)
  // Audio: "Now choose your match rounds. Then, click Copy Invite Link or share your room code so your crew can jump into the lobby."
  // ──────────────────────────────────────────────────────────────────────────
  await runScene(3, async () => {
    // 0.0s - 2.4s: "Now choose your match rounds." -> Smooth 650ms zoom to Match Configuration panel
    await smoothCameraToElement(page, '#modeCard-frames', { scale: 1.15, dur: 650, offsetY: 25 });
    await glideAndClick(page, '#modeCard-frames button[title="Increase Rounds"]', 380, 400);
    await delay(300);

    // 2.4s - 4.6s: "Then, click Copy Invite Link..." -> Glide up to Copy Link button, click
    await glideAndClick(page, 'button:has-text("Copy Link")', 400, 400);
    await delay(300);

    // 4.6s - 7.73s: "...or share your room code so your crew can jump into the lobby." -> Gentle 600ms drift to center lobby players
    await smoothCameraToElement(page, '#lobbyPlayerList', { scale: 1.10, dur: 600 });

    // 3 Friends join the lobby in sequence
    await delay(300);
    await page.evaluate(() => {
      GS.players = [
        { id: 'p1', name: 'Aman', avatar: 'aman', score: 0, isHost: true, color: '#ff6b9d', loaded: true },
        { id: 'p2', name: 'Amish', avatar: 'amish', score: 0, isHost: false, color: '#3b82f6', loaded: true }
      ];
      PlayerLobby.render();
    });
    await delay(500);
    await page.evaluate(() => {
      GS.players.push({ id: 'p3', name: 'Aziz', avatar: 'aziz', score: 0, isHost: false, color: '#84cc16', loaded: true });
      PlayerLobby.render();
    });
    await delay(500);
    await page.evaluate(() => {
      GS.players.push({ id: 'p4', name: 'Vish', avatar: 'vish', score: 0, isHost: false, color: '#facc15', loaded: true });
      PlayerLobby.render();
      const btn = document.getElementById('lobbyStartBtn');
      if (btn) {
        btn.disabled = false;
        btn.style.opacity = '1';
        btn.style.cursor = 'pointer';
      }
    });
  });

  // ──────────────────────────────────────────────────────────────────────────
  // SCENE 4: Start Game & 10-Second Quick Guide (8.376s)
  // Audio: "Once everyone is in, click Start Game. You'll have ten seconds to review the quick rules, or the host can launch round one immediately."
  // ──────────────────────────────────────────────────────────────────────────
  await runScene(4, async () => {
    // 0.0s - 2.0s: "Once everyone is in, click Start Game." -> Reset camera, glide to Start Game
    await resetCamera(page, 500);
    await glideAndClick(page, '#lobbyStartBtn', 380, 250);
    await page.evaluate(() => {
      PlayerLobby.start();
      // Remove "STEP 1:", "STEP 2:", "STEP 3:" prefixes from quick guide modal
      document.querySelectorAll('.hta-step-title').forEach(el => {
        el.textContent = el.textContent.replace(/^STEP\s*\d+:\s*/i, '').trim();
      });
    });

    // 2.0s - 5.5s: "You'll have ten seconds to review the quick rules," -> Smooth 650ms zoom into Quick Guide modal
    // Camera remains rock-solid stable while cursor glides smoothly across the 3 cards!
    await smoothCameraToElement(page, '.hta-modal-card', { scale: 1.14, dur: 650 });
    await glideCursorToElement(page, '.hta-step-card.step-1', 400); // Watch Frame
    await delay(450);
    await glideCursorToElement(page, '.hta-step-card.step-2', 400); // Type Guess
    await delay(450);
    await glideCursorToElement(page, '.hta-step-card.step-3', 400); // Unlimited Tries
    await delay(450);
    await glideCursorToElement(page, '.hta-score-pill.pill-gold', 400); // Pointing system (+10 pts)
    await delay(450);

    // 5.5s - 8.38s: "or the host can launch round one immediately." -> Host unlocks & clicks Start Game
    await page.evaluate(() => {
      HowToAnswerGuide._secondsLeft = 0;
      const hostBtn = document.getElementById('htaHostStartBtn');
      if (hostBtn) {
        hostBtn.disabled = false;
        hostBtn.innerHTML = '<span class="hta-play-icon">▶</span> <span class="hta-btn-text">START GAME</span>';
        hostBtn.style.animation = 'pulse 1.2s infinite';
      }
    });
    await delay(200);
    await glideAndClick(page, '#htaHostStartBtn', 380, 500);
  });

  // ──────────────────────────────────────────────────────────────────────────
  // SCENE 5: Active Round & Live Chat Guessing (11.808s)
  // Audio: "Round one is live! Look at the screenshot and type your movie guesses into the live chat. First correct answer gets 10 points, second gets 7, and third gets 5 points!"
  // ──────────────────────────────────────────────────────────────────────────
  await runScene(5, async () => {
    await page.evaluate(() => {
      const ov = document.getElementById('roundIntroOv');
      if (ov) ov.classList.remove('on');
      UI.renderLB();
    });

    // 0.0s - 3.2s: "Round one is live! Look at the screenshot" -> Smooth 650ms zoom to cinema frame
    await smoothCameraToElement(page, '.frame-area', { scale: 1.18, dur: 650 });
    await delay(1800);

    // 3.2s - 6.5s: "and type your movie guesses into the live chat." -> Smooth 680ms dolly pan to Live Chat
    await smoothCameraToElement(page, '#liveChatPanel', { scale: 1.20, dur: 680 });
    await typeTextHuman(page, '#chatTextInput', 'Hera Pheri', 55);
    await glideAndClick(page, '#chatSendBtn', 320, 250);

    // 6.5s - 11.81s: "First correct answer gets 10 points, second gets 7, and third gets 5 points!"
    // Aman +10 pts banner
    await page.evaluate(() => {
      ChatEngine.renderWinnerBanner({
        playerId: 'p1',
        playerName: 'Aman',
        avatar: 'aman',
        position: 1,
        points: 10
      });
      const aman = GS.players.find(p => p.name.toLowerCase() === 'aman');
      if (aman) aman.score = 10;
      UI.renderLB();
    });
    await delay(1200);

    // Amish +7 pts
    await page.evaluate(() => {
      const amish = GS.players.find(p => p.name.toLowerCase() === 'amish');
      if (amish) amish.score = 7;
      UI.renderLB();
    });
    await delay(1100);

    // Aziz +5 pts
    await page.evaluate(() => {
      const aziz = GS.players.find(p => p.name.toLowerCase() === 'aziz');
      if (aziz) aziz.score = 5;
      UI.renderLB();
    });
    await delay(800);
  });

  // ──────────────────────────────────────────────────────────────────────────
  // SCENE 6: Using the Hint Feature (6.552s)
  // Audio: "Stuck on a tricky frame? Tap the Hint button to reveal missing letter blanks and solve the movie title."
  // ──────────────────────────────────────────────────────────────────────────
  await runScene(6, async () => {
    // 0.0s - 2.5s: "Stuck on a tricky frame? Tap the Hint button" -> Smooth 600ms zoom to Hint area, click
    await smoothCameraToElement(page, '#chatHintBtn', { scale: 1.24, dur: 600 });
    await glideAndClick(page, '#chatHintBtn', 350, 200);

    // 2.5s - 6.55s: "to reveal missing letter blanks and solve the movie title." -> Missing blanks banner animates in
    await page.evaluate(() => {
      ChatEngine.renderPersonalHintMessage('H _ _ A   P _ _ _ I');
      const pill = document.getElementById('chatActiveHint');
      const text = document.getElementById('chatActiveHintText');
      if (pill && text) {
        pill.style.display = 'block';
        text.textContent = 'H _ _ A   P _ _ _ I';
      }
    });
    await delay(500);
    // Cursor smoothly underlines the revealed blanks
    await glideCursorToElement(page, '#chatActiveHint', 400);
    await delay(800);
  });

  // ──────────────────────────────────────────────────────────────────────────
  // SCENE 7: Host Controls: Pause, Skip, End Early (8.664s)
  // Audio: "As the host, you're in full control. You can pause the round timer, skip an impossible frame, or end the game early at any time."
  // ──────────────────────────────────────────────────────────────────────────
  await runScene(7, async () => {
    await page.evaluate(() => {
      const hBar = document.getElementById('hostFloatingBar');
      if (hBar) {
        hBar.style.display = 'flex';
        hBar.style.opacity = '1';
      }
      const hfb = document.getElementById('hfbHostOnly');
      if (hfb) hfb.style.display = 'inline-flex';
    });

    // 0.0s - 2.8s: "As the host, you're in full control. You can pause the round timer," -> Smooth 650ms zoom to host toolbar
    await smoothCameraToElement(page, '#hostFloatingBar', { scale: 1.20, dur: 650 });
    await glideCursorToElement(page, '#hfbPauseBtn', 450);
    await delay(1200);

    // 2.8s - 5.2s: "skip an impossible frame," -> Glide to Skip Frame
    await glideCursorToElement(page, '#hfbSkipBtn', 450);
    await delay(1200);

    // 5.2s - 8.66s: "or end the game early at any time." -> Glide to End Match
    await glideCursorToElement(page, 'button:has-text("End Match")', 450);
    await delay(1000);
  });

  // ──────────────────────────────────────────────────────────────────────────
  // SCENE 8: Timer Ends, Answer Reveal & Next Round (7.680s)
  // Audio: "When time runs out, the movie and trivia are revealed. The host simply clicks Next Round to keep the competition rolling."
  // ──────────────────────────────────────────────────────────────────────────
  await runScene(8, async () => {
    await page.evaluate(() => {
      TC.stop();
      if (typeof HowToAnswerGuide !== 'undefined') HowToAnswerGuide.stop();

      const ao = document.getElementById('answerOverlay');
      const at = document.getElementById('ansTitle');
      const ay = document.getElementById('ansYear');
      const ad = document.getElementById('ansDialogue');
      const nextBtn = document.getElementById('ansNextRoundBtn');

      if (at) at.textContent = 'HERA PHERI';
      if (ay) ay.textContent = '(2000) • DIRECTED BY PRIYADARSHAN';
      if (ad) {
        ad.innerHTML = `
          <div style="font-size: 1.15rem; color: #ffd166; font-style: italic; margin-bottom: 12px;">"Yeh Baburao ka style hai!"</div>
          <div class="winners-spotlight">
            <div class="winner-pill winner-pill-1"><span>🥇 Aman</span><span>+10 pts</span></div>
            <div class="winner-pill winner-pill-2"><span>🥈 Amish</span><span>+7 pts</span></div>
            <div class="winner-pill winner-pill-3"><span>🥉 Aziz</span><span>+5 pts</span></div>
          </div>
        `;
      }

      if (nextBtn) {
        nextBtn.style.display = 'inline-flex';
        nextBtn.textContent = 'NEXT ROUND ⏭';
      }

      if (ao) {
        ao.style.display = 'flex';
        ao.style.opacity = '1';
        ao.style.pointerEvents = 'auto';
        ao.classList.add('visible', 'active');
      }

      MultiplayerEngine.hostNextRound = () => {
        if (nextBtn) {
          nextBtn.style.transform = 'scale(0.95)';
          setTimeout(() => { nextBtn.style.transform = ''; }, 150);
        }
      };
    });

    // 0.0s - 4.0s: "When time runs out, the movie and trivia are revealed." -> Smooth 650ms zoom on Answer card
    await smoothCameraToElement(page, '#answerOverlay .ans-card, #answerOverlay', { scale: 1.16, dur: 650 });
    await delay(2600);

    // 4.0s - 7.68s: "The host simply clicks Next Round to keep the competition rolling." -> Glide & click Next Round
    await glideAndClick(page, '#ansNextRoundBtn', 400, 600);
  });

  // ──────────────────────────────────────────────────────────────────────────
  // SCENE 9: Crown the Champion Podium (8.136s)
  // Audio: "After the final round, the player with the most points is crowned champion on the victory podium! Rematch your friends and play again."
  // ──────────────────────────────────────────────────────────────────────────
  await runScene(9, async () => {
    await page.evaluate(() => {
      const ao = document.getElementById('answerOverlay');
      if (ao) {
        ao.style.display = 'none';
        ao.classList.remove('visible', 'active');
      }
      WinnerScreen.show([
        { name: 'AMAN', score: 30, avatar: 'aman' },
        { name: 'AMISH', score: 15, avatar: 'amish' },
        { name: 'AZIZ', score: 10, avatar: 'aziz' },
        { name: 'VISH', score: 5, avatar: 'vish' }
      ]);
    });

    // 0.0s - 4.2s: "After the final round, the player with the most points is crowned champion..." -> Smooth 650ms zoom on winner podium
    await smoothCameraToElement(page, '#winnerStage, .winner-screen, #winnerModal', { scale: 1.12, dur: 650 });

    // Confetti popper explosion
    await page.evaluate(() => {
      if (WinnerScreen.triggerPopper) {
        WinnerScreen.triggerPopper('left');
        setTimeout(() => WinnerScreen.triggerPopper('right'), 250);
      }
    });

    await glideCursorToElement(page, '#champHeroCard, .runner-gold', 450, 640, 380); // 1st place Aman
    await delay(600);
    await glideCursorToElement(page, '#silverCard, .runner-blue', 380, 440, 440);  // 2nd place Amish
    await delay(400);
    await glideCursorToElement(page, '#bronzeCard, .runner-orange', 380, 840, 440);  // 3rd place Aziz
    await delay(600);

    // 4.2s - 8.14s: "Rematch your friends and play again." -> Smooth 700ms ease out to wide view, glide to REMATCH
    await resetCamera(page, 700);
    await glideCursorToElement(page, '.btn-rematch', 400, 640, 660); // Rematch button
    await delay(1200);
  });

  console.log('\n🎉 Recording complete with frame-accurate sync and silky-smooth zooms!');

  await context.close();
  await browser.close();

  // Find latest recorded webm video
  const videoFiles = fs.readdirSync(RECORD_DIR).filter(f => f.startsWith('page@') && f.endsWith('.webm'));
  if (videoFiles.length > 0) {
    const latestVideo = videoFiles.map(f => ({
      name: f,
      time: fs.statSync(path.join(RECORD_DIR, f)).mtimeMs
    })).sort((a, b) => b.time - a.time)[0].name;

    const rawPath = path.join(RECORD_DIR, latestVideo);
    const targetRawPath = path.join(RECORD_DIR, 'raw_tutorial_v2.webm');
    fs.copyFileSync(rawPath, targetRawPath);
    console.log(`✅ Raw Recording saved: ${targetRawPath}`);

    // Exact dynamic pre-roll offset
    const offsetSec = Number(preRollOffsetSec.toFixed(3));
    console.log(`🎬 Trimming raw video at exact dynamic pre-roll offset: ${offsetSec}s...`);

    const masterAudio = path.join(RECORD_DIR, 'narration_master.mp3');

    // 1. HD 60 FPS Video (1280x720)
    const hdOutput = path.join(RECORD_DIR, 'guess_the_frame_tutorial_pro.mp4');
    const ffmpegHd = `ffmpeg -y -i "${targetRawPath}" -i "${masterAudio}" -filter_complex "[0:v]trim=start=${offsetSec},setpts=PTS-STARTPTS,fps=fps=60,fade=t=out:st=69:d=1.5[v];[1:a]afade=t=out:st=69:d=1.5[a]" -map "[v]" -map "[a]" -c:v libx264 -preset medium -crf 17 -pix_fmt yuv420p -c:a aac -b:a 192k -r 60 -t 70.536 "${hdOutput}"`;
    console.log(`Running HD FFmpeg muxing:\n${ffmpegHd}`);
    execSync(ffmpegHd, { stdio: 'inherit' });

    // 2. 4K UHD 60 FPS Master Video (3840x2160 Lanczos sinc supersampling)
    const uhdOutput = path.join(RECORD_DIR, 'guess_the_frame_tutorial_4k.mp4');
    const ffmpeg4k = `ffmpeg -y -i "${targetRawPath}" -i "${masterAudio}" -filter_complex "[0:v]trim=start=${offsetSec},setpts=PTS-STARTPTS,fps=fps=60,scale=3840:2160:flags=lanczos+accurate_rnd,fade=t=out:st=69:d=1.5[v];[1:a]afade=t=out:st=69:d=1.5[a]" -map "[v]" -map "[a]" -c:v libx264 -preset veryfast -crf 16 -pix_fmt yuv420p -c:a aac -b:a 192k -r 60 -t 70.536 "${uhdOutput}"`;
    console.log(`Running 4K FFmpeg muxing:\n${ffmpeg4k}`);
    execSync(ffmpeg4k, { stdio: 'inherit' });

    // Copy to root directory
    const rootHd = path.resolve(__dirname, '../guess_the_frame_tutorial_pro.mp4');
    const root4k = path.resolve(__dirname, '../guess_the_frame_tutorial_4k.mp4');
    fs.copyFileSync(hdOutput, rootHd);
    fs.copyFileSync(uhdOutput, root4k);
    console.log(`✅ Copied to project root:\n - ${root4k}\n - ${rootHd}`);

    // Copy to artifact directory
    if (fs.existsSync(ARTIFACT_DIR)) {
      fs.copyFileSync(uhdOutput, path.join(ARTIFACT_DIR, 'guess_the_frame_tutorial_4k.mp4'));
      fs.copyFileSync(hdOutput, path.join(ARTIFACT_DIR, 'guess_the_frame_tutorial_pro.mp4'));
      console.log(`✅ Copied to artifact directory: ${ARTIFACT_DIR}`);
    }
  }
})();
